[package]
name = "alfred-openai"
version = "0.1.0"
edition = "2021"

[dependencies]
openai-api-rs = "4.1.1"
alfred-rs = { path = "../alfred-rs" }
tokio = "1.37.0"
env_logger = "0.11.3"
uuid = { version = "1.9.1", features = ["v4"] }
reqwest = { version = "0.12.5", features = ["multipart", "json"] }
serde = { version = "1.0.202", features = ["derive"] }