[alfred]
url = "tcp://127.0.0.1"
pub_port = 5678
sub_port = 1234

[openai]
openai_api_key = ""
system_msg = ""
enable_tts = "true"
tts_model = "tts-1"
tts_voice = "alloy"
enable_stt = "true"
stt_model = "whisper-1"
